name: Trigger auto deployment for analytics-service-academy-iq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/analytics-service-academy-iq-AutoDeployTrigger-8402984a-dcef-4e5f-88ac-69889b8e1bab.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ANALYTICSSERVICEACADEMYIQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ANALYTICSSERVICEACADEMYIQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ANALYTICSSERVICEACADEMYIQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: academyiq.azurecr.io
          registryUsername: ${{ secrets.ANALYTICSSERVICEACADEMYIQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANALYTICSSERVICEACADEMYIQ_REGISTRY_PASSWORD }}
          containerAppName: analytics-service-academy-iq
          resourceGroup: ds-assignment-y3-s1-resource-group
          imageToBuild: academyiq.azurecr.io/analytics-service-academy-iq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
          allowInsecureConnections: true
          allowPublicNetworkAccess: true


